import ProviderResizable from "@/provider/provider-resizable";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Spotify Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div id="app">
					<ProviderResizable>{children}</ProviderResizable>
					<section className="p-2">Bottom section</section>
				</div>
			</body>
		</html>
	);
}
