import ContentHeader from "@/components/content/content-header";
import Sidebar from "@/components/sidebar/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div id="app">
					<div className="flex flex-1 gap-2">
						<Sidebar />
						<div className="bg-neutral-900 rounded-lg w-full overflow-hidden">
							<ContentHeader />
							<main>{children}</main>
						</div>
					</div>
					<section className="p-2">Bottom section</section>
				</div>
			</body>
		</html>
	);
}
